# Generated by Django 5.2.1 on 2025-06-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_alter_category_options_rename_category_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
