# Generated by Django 5.2.1 on 2025-06-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_advertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
