# Generated by Django 5.2.1 on 2025-06-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0008_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_at']},
        ),
    ]
